export type ApiMethod = 'GET' | 'POST' | 'DELETE';

export interface ApiParamMetadata {
	name: string;
	required?: boolean;
	description?: string;
	defaultValue?: string | number | boolean;
	example?: string | number | boolean;
	enumValues?: Array<string | number | boolean>;
}

export interface ApiExampleMetadata {
	label: string;
	params?: Record<string, unknown>;
	body?: unknown;
}

export interface ApiMetadataItem {
	name: string;
	category: string;
	method: ApiMethod;
	path: string;
	aliases?: string[];
	description?: string;
	queryParams?: ApiParamMetadata[];
	pathParams?: ApiParamMetadata[];
	bodyExample?: unknown;
	examples?: ApiExampleMetadata[];
	authRequired?: boolean;
	cookieRequired?: boolean;
}

const paramMetadataByName: Record<string, Omit<ApiParamMetadata, 'name'>> = {
	albumid: { description: 'QQ Music album numeric ID. Optional when albummid is provided.' },
	albummid: {
		description: 'QQ Music album MID.',
		example: '002MAeob3zLXwZ',
	},
	area: { description: 'Singer area filter. -1 or -100 means all areas.', defaultValue: -1 },
	areaId: {
		description: 'New song area/type ID.',
		defaultValue: 5,
		enumValues: [1, 2, 3, 4, 5],
	},
	area_id: { description: 'MV area ID.', defaultValue: 15 },
	begin: { description: 'Zero-based result offset.', defaultValue: 0 },
	biztype: {
		description: 'Comment business type. 1 song, 2 playlist, 3 album.',
		defaultValue: 1,
		enumValues: [1, 2, 3],
	},
	categoryId: { description: 'Playlist category ID.', defaultValue: 10000000 },
	catZhida: {
		description: 'Whether to include QQ Music zhida direct-hit results.',
		defaultValue: 1,
		enumValues: [0, 1],
	},
	cid: { description: 'QQ Music comment topic category ID.', defaultValue: 205360772 },
	cmd: { description: 'QQ Music comment command.', defaultValue: 8 },
	date: {
		description: 'Date string (YYYY-MM-DD). Used by listening calendar to scope the queried month.',
		example: '2026-07-01',
	},
	cookie: {
		description: 'QQ Music cookie. Used for login-required or member-only data. Values are never shown by MCP.',
	},
	disstid: {
		description: 'QQ Music playlist disstid.',
		example: '8724912747',
	},
	genre: { description: 'Singer genre filter. -1 or -100 means all genres.', defaultValue: -1 },
	id: {
		description: 'Resource ID used by this endpoint, such as song ID, album MID, image MID, or comment target.',
	},
	index: { description: 'Singer name initial index. -100 means all initials.', defaultValue: -100 },
	isFormat: {
		description: 'Whether to parse and format lyric lines.',
		defaultValue: false,
		enumValues: [false, true],
	},
	k: { description: 'QQ avatar key. Alternative to uin for getUserAvatar.' },
	key: {
		description: 'Search keyword.',
		example: '周杰伦',
	},
	lastId: { description: 'Pagination cursor from the previous related-playlist response.' },
	lastid: {
		description: 'Pagination cursor from the previous dislike-list response. Maps to SongLastid/SingersLastid/StyleLastid by cmd.',
	},
	lastmvid: { description: 'Pagination cursor from the previous related-MV response.' },
	limit: { description: 'Maximum number of items to return.', defaultValue: 20 },
	maxAge: {
		description: 'Image CDN max_age query value in seconds.',
		defaultValue: 2592000,
	},
	mediaId: { description: 'QQ Music media ID. Defaults to songmid when omitted.' },
	num: { description: 'Maximum number of items to return.', defaultValue: 20 },
	offset: { description: 'Zero-based result offset.', defaultValue: 0 },
	order: { description: 'Sort order accepted by the upstream endpoint.' },
	page: { description: 'Page number.', defaultValue: 1 },
	pagenum: { description: 'Comment page number, starting from 0.', defaultValue: 0 },
	pagesize: { description: 'Number of items per page.', defaultValue: 20 },
	quality: {
		description: 'Preferred audio quality for play URLs.',
		defaultValue: '128',
		enumValues: ['m4a', '128', '320', 'ape', 'flac'],
	},
	remoteplace: {
		description: 'Search source. Short values are normalized to txt.yqq.* by MCP.',
		defaultValue: 'song',
		enumValues: ['song', 'album', 'mv', 'singer', 'playlist', 'txt.yqq.song'],
	},
	reqtype: { description: 'QQ Music comment request type.', defaultValue: 2 },
	resType: {
		description: 'Return only playUrl or the raw upstream vkey payload.',
		defaultValue: 'play',
		enumValues: ['play', 'raw'],
	},
	rootcommentid: { description: 'Last hot comment ID cursor required by some comment pages.' },
	sex: { description: 'Singer gender filter. -1 or -100 means all genders.', defaultValue: -1 },
	sin: { description: 'Zero-based offset for related playlist results.', defaultValue: 0 },
	singermid: {
		description: 'QQ Music singer MID.',
		example: '0025NhlN2yWrP4',
	},
	size: {
		description: 'Image or avatar size.',
		defaultValue: '300x300',
		example: '300x300',
	},
	songid: { description: 'QQ Music numeric song ID.', example: '97773' },
	songmid: {
		description: 'QQ Music song MID. Multiple values can be comma-separated where supported.',
		example: '0039MnYb0qxYhV',
	},
	songType: { description: 'Related playlist song type.', defaultValue: 0 },
	songtype: { description: 'Related MV song type.', defaultValue: 0 },
	sortId: { description: 'Playlist sort ID. 5 usually means latest or recommended sort.', defaultValue: 5 },
	tabId: {
		description: 'Medal category tab ID. 2 usually means 乐迷 (music fan).',
		defaultValue: 2,
	},
	tagId: { description: 'Playlist tag ID from getPlaylistTags.', defaultValue: 1 },
	topId: { description: 'Ranking list ID.', defaultValue: 4 },
	type: {
		description: 'Resource or recommendation type.',
		defaultValue: 1,
	},
	euin: {
		description: 'Encrypted QQ Music UIN returned in the login session. Required by user profile RPCs.',
	},
	uin: {
		description: 'QQ user UIN. Some MCP adapters also accept id as an alias.',
		example: '123456789',
	},
	version_id: { description: 'MV version/category ID.', defaultValue: 7 },
	vid: {
		description: 'QQ Music MV video ID.',
		example: 's0046w1f7i5',
	},
};

const metadata = (param: ApiParamMetadata): ApiParamMetadata => ({
	...paramMetadataByName[param.name],
	...param,
});

const params = (items: ApiParamMetadata[]): ApiParamMetadata[] => items.map(metadata);

const withDefaultParamMetadata = (item: ApiMetadataItem): ApiMetadataItem => ({
	...item,
	queryParams: item.queryParams ? params(item.queryParams) : undefined,
	pathParams: item.pathParams ? params(item.pathParams) : undefined,
});

const rawApiMetadata: ApiMetadataItem[] = [
	{
		name: 'getCookie',
		category: 'user',
		method: 'GET',
		path: '/user/getCookie',
		description: 'Read the locally stored QQ Music cookie status.',
	},
	{
		name: 'setCookie',
		category: 'user',
		method: 'GET',
		path: '/user/setCookie',
		description: 'Store a QQ Music cookie locally.',
		queryParams: params([{ name: 'cookie', required: true }]),
	},
	{
		name: 'getUserPlaylists',
		category: 'user',
		method: 'GET',
		path: '/user/getUserPlaylists',
		description: 'List playlists created by a QQ Music user.',
		queryParams: params([
			{ name: 'uin', required: true },
			{ name: 'offset' },
			{ name: 'limit', defaultValue: 30 },
			{ name: 'cookie' },
		]),
		cookieRequired: true,
		examples: [{ label: 'User playlists', params: { uin: '123456789', offset: 0, limit: 30 } }],
	},
	{
		name: 'getUserDetail',
		category: 'user',
		method: 'GET',
		path: '/user/getUserDetail',
		description: 'Fetch public profile details for a QQ Music user.',
		queryParams: params([{ name: 'uin', required: true }, { name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getUserCollectedSongLists',
		category: 'user',
		method: 'GET',
		path: '/user/getUserCollectedSongLists',
		description: 'List playlists collected by a QQ Music user.',
		queryParams: params([{ name: 'uin', required: true }, { name: 'page' }, { name: 'limit' }, { name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getUserCollectedAlbums',
		category: 'user',
		method: 'GET',
		path: '/user/getUserCollectedAlbums',
		description: 'List albums collected by a QQ Music user.',
		queryParams: params([{ name: 'uin', required: true }, { name: 'page' }, { name: 'limit' }, { name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getUserFollowSingers',
		category: 'user',
		method: 'GET',
		path: '/user/getUserFollowSingers',
		description: 'List singers followed by a QQ Music user.',
		queryParams: params([{ name: 'uin', required: true }, { name: 'page' }, { name: 'limit' }, { name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getUserFollowUsers',
		category: 'user',
		method: 'GET',
		path: '/user/getUserFollowUsers',
		description: 'List users followed by a QQ Music user.',
		queryParams: params([{ name: 'uin', required: true }, { name: 'page' }, { name: 'limit' }, { name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getUserFans',
		category: 'user',
		method: 'GET',
		path: '/user/getUserFans',
		description: 'List fans of a QQ Music user.',
		queryParams: params([{ name: 'uin', required: true }, { name: 'page' }, { name: 'limit' }, { name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getUserAvatar',
		category: 'user',
		method: 'GET',
		path: '/user/getUserAvatar',
		description: 'Build a QQ user avatar URL from uin or avatar key.',
		queryParams: params([
			{ name: 'uin' },
			{ name: 'k' },
			{ name: 'size', defaultValue: 140, example: 140, enumValues: [40, 100, 140, 640] },
		]),
	},
	{
		name: 'getUserLikedSongs',
		category: 'user',
		method: 'GET',
		path: '/user/getUserLikedSongs',
		description: 'List liked songs for a QQ Music user.',
		queryParams: params([
			{ name: 'uin', required: true },
			{ name: 'offset' },
			{ name: 'limit', defaultValue: 30 },
			{ name: 'cookie' },
		]),
		cookieRequired: true,
	},
	{
		name: 'getUserMedal',
		category: 'user',
		method: 'GET',
		path: '/user/getUserMedal',
		description: 'Fetch the medal hall homepage header (sound power, medal totals, category stats).',
		queryParams: params([{ name: 'euin' }, { name: 'cookie', required: true }]),
		cookieRequired: true,
	},
	{
		name: 'getMedalTabDetail',
		category: 'user',
		method: 'GET',
		path: '/user/getMedalTabDetail',
		description: 'List medals under a specific medal category tab. euin may be passed explicitly or come from the stored login session.',
		queryParams: params([{ name: 'tabId', required: true }, { name: 'euin' }, { name: 'cookie', required: true }]),
		cookieRequired: true,
	},
	{
		name: 'getHideMedal',
		category: 'user',
		method: 'GET',
		path: '/user/getHideMedal',
		description: 'List hidden/mystery medals. euin may be passed explicitly or come from the stored login session.',
		queryParams: params([{ name: 'euin' }, { name: 'cookie', required: true }]),
		cookieRequired: true,
	},
	{
		name: 'getListeningCalendar',
		category: 'user',
		method: 'GET',
		path: '/user/getListeningCalendar',
		description: 'Fetch the listening calendar (consecutive days, daily play records). euin may be passed explicitly or come from the stored login session.',
		queryParams: params([{ name: 'date' }, { name: 'euin' }, { name: 'cookie', required: true }]),
		cookieRequired: true,
	},
	{
		name: 'getVipInfo',
		category: 'user',
		method: 'GET',
		path: '/user/getVipInfo',
		description: 'Fetch VIP membership details (expiry,豪华VIP, audio effect permissions).',
		queryParams: params([{ name: 'cookie', required: true }]),
		cookieRequired: true,
	},
	{
		name: 'getFriendList',
		category: 'user',
		method: 'GET',
		path: '/user/getFriendList',
		description: 'List QQ Music friends of the current logged-in user.',
		queryParams: params([{ name: 'page' }, { name: 'limit' }, { name: 'cookie', required: true }]),
		cookieRequired: true,
	},
	{
		name: 'getMusicGene',
		category: 'user',
		method: 'GET',
		path: '/user/getMusicGene',
		description: 'Fetch the music gene report (top singers, music age, genre preferences). euin may be passed explicitly or come from the stored login session.',
		queryParams: params([{ name: 'euin' }, { name: 'cookie', required: true }]),
		cookieRequired: true,
	},
	{
		name: 'getUserFavMv',
		category: 'user',
		method: 'GET',
		path: '/user/getUserFavMv',
		description: 'List MVs favorited by the current user. euin may be passed explicitly or come from the stored login session.',
		queryParams: params([{ name: 'page' }, { name: 'limit' }, { name: 'euin' }, { name: 'cookie', required: true }]),
		cookieRequired: true,
	},
	{
		name: 'getDislikeList',
		category: 'user',
		method: 'GET',
		path: '/user/getDislikeList',
		description: 'List disliked items (songs/singers/styles). cmd selects the category; lastid is the pagination cursor.',
		queryParams: params([
			{ name: 'cmd', defaultValue: 3, enumValues: [2, 3, 4], description: '2=歌手 / 3=歌曲 / 4=风格' },
			{ name: 'page' },
			{ name: 'lastid' },
			{ name: 'cookie', required: true },
		]),
		cookieRequired: true,
	},
	{
		name: 'getDownloadQQMusic',
		category: 'download',
		method: 'GET',
		path: '/downloadQQMusic',
		description: 'Fetch QQ Music client download metadata.',
	},
	{
		name: 'getHotKey',
		category: 'search',
		method: 'GET',
		path: '/getHotkey',
		description: 'Fetch public QQ Music search hot keywords.',
	},
	{
		name: 'getSearchByKey',
		category: 'search',
		method: 'GET',
		path: '/getSearchByKey',
		aliases: ['/getSearchByKey/:key'],
		description: 'Search QQ Music by keyword across songs and other content types.',
		queryParams: params([
			{ name: 'key', required: true },
			{ name: 'limit', defaultValue: 10 },
			{ name: 'page' },
			{ name: 'catZhida' },
			{ name: 'remoteplace' },
		]),
		examples: [{ label: 'Song search', params: { key: '周杰伦', limit: 10, page: 1, remoteplace: 'song' } }],
	},
	{
		name: 'getSmartbox',
		category: 'search',
		method: 'GET',
		path: '/getSmartbox',
		aliases: ['/getSmartbox/:key'],
		description: 'Fetch QQ Music smart search suggestions.',
		queryParams: params([{ name: 'key', required: true }]),
	},
	{
		name: 'getSongListCategories',
		category: 'playlist',
		method: 'GET',
		path: '/getSongListCategories',
		description: 'List QQ Music playlist categories.',
	},
	{
		name: 'getSongLists',
		category: 'playlist',
		method: 'GET',
		path: '/getSongLists',
		aliases: ['/getSongLists/:page/:limit/:categoryId/:sortId'],
		description: 'List playlists by category and sort order.',
		queryParams: params([
			{ name: 'limit' },
			{ name: 'page', defaultValue: 0, description: 'Zero-based playlist page.' },
			{ name: 'sortId' },
			{ name: 'categoryId' },
		]),
	},
	{
		name: 'batchGetSongLists',
		category: 'playlist',
		method: 'POST',
		path: '/batchGetSongLists',
		description: 'Fetch multiple playlist details by ID.',
		bodyExample: { ids: ['123'] },
		examples: [{ label: 'Batch playlists', body: { ids: ['123'] } }],
	},
	{
		name: 'getSongInfo',
		category: 'music',
		method: 'GET',
		path: '/getSongInfo',
		aliases: ['/getSongInfo/:songmid'],
		description: 'Fetch song details by songmid or songid.',
		queryParams: params([{ name: 'songmid', required: true }, { name: 'songid' }]),
	},
	{
		name: 'batchGetSongInfo',
		category: 'music',
		method: 'POST',
		path: '/batchGetSongInfo',
		description: 'Fetch multiple song detail records.',
		bodyExample: { songs: [['songmid', 'songid']] },
		examples: [{ label: 'Batch songs', body: { songs: [['0039MnYb0qxYhV', '97773']] } }],
	},
	{
		name: 'getSongListDetail',
		category: 'playlist',
		method: 'GET',
		path: '/getSongListDetail',
		aliases: ['/getSongListDetail/:disstid'],
		description: 'Fetch playlist details by disstid.',
		queryParams: params([{ name: 'disstid', required: true }]),
	},
	{
		name: 'resolveSongListShareUrl',
		category: 'playlist',
		method: 'GET',
		path: '/resolveSongListShareUrl',
		aliases: ['/resolveSongListShareUrl/:url'],
		description:
			'Parse a QQ Music playlist share URL (i2.y.qq.com playlist.html?id=..., y.qq.com/n/ryqq/playlist/<id>, etc.) and return the playlist details directly. Only numeric disstid URLs are supported; alphanumeric MID URLs return 400.',
		queryParams: params([
			{
				name: 'url',
				required: true,
				description: 'QQ Music playlist share URL. Plain URL or text containing a URL is accepted.',
				example:
					'https://i2.y.qq.com/n3/other/pages/details/playlist.html?platform=11&appshare=android_qq&appversion=20040008&hosteuin=oKElNKviowv57n**&id=2029866739&ADTAG=qfshare',
			},
		]),
		examples: [
			{
				label: 'Resolve share URL',
				params: {
					url: 'https://i2.y.qq.com/n3/other/pages/details/playlist.html?id=2029866739',
				},
			},
			{
				label: 'Resolve ryqq path URL',
				params: { url: 'https://y.qq.com/n/ryqq/playlist/2029866739' },
			},
		],
	},
	{
		name: 'getAlbumSongs',
		category: 'album',
		method: 'GET',
		path: '/getAlbumSongs',
		aliases: ['/getAlbumSongs/:albummid'],
		description: 'List songs in an album.',
		queryParams: params([
			{ name: 'albummid', required: true },
			{ name: 'albumid' },
			{ name: 'begin' },
			{ name: 'limit' },
			{ name: 'order', defaultValue: 2 },
		]),
	},
	{
		name: 'getNewDisks',
		category: 'album',
		method: 'GET',
		path: '/getNewDisks',
		description: 'List new album releases.',
		queryParams: params([{ name: 'page' }, { name: 'limit' }]),
	},
	{
		name: 'getMvByTag',
		category: 'mv',
		method: 'GET',
		path: '/getMvByTag',
		description: 'List MV data grouped by upstream tags.',
	},
	{
		name: 'getMv',
		category: 'mv',
		method: 'GET',
		path: '/getMv',
		description: 'List MV entries by area and version filters.',
		queryParams: params([
			{ name: 'area_id' },
			{ name: 'version_id' },
			{ name: 'limit' },
			{ name: 'page', defaultValue: 0, description: 'MV page number. 0 and 1 both start at the first page.' },
		]),
	},
	{
		name: 'getMvCategory',
		category: 'mv',
		method: 'GET',
		path: '/getMvCategory',
		description: 'List MV category filters.',
	},
	{
		name: 'getMvPlay',
		category: 'mv',
		method: 'GET',
		path: '/getMvPlay',
		description: 'Fetch MV metadata and playable URL groups by video ID.',
		queryParams: params([{ name: 'vid', required: true }]),
	},
	{
		name: 'getSingerList',
		category: 'singer',
		method: 'GET',
		path: '/getSingerList',
		description: 'List singers by area, gender, genre, and initial filters.',
		queryParams: params([
			{ name: 'area', defaultValue: -100 },
			{ name: 'sex', defaultValue: -100 },
			{ name: 'genre', defaultValue: -100 },
			{ name: 'index' },
			{ name: 'page' },
		]),
	},
	{
		name: 'getSingerCategory',
		category: 'singer',
		method: 'GET',
		path: '/getSingerCategory',
		description: 'List singer category filters.',
	},
	{
		name: 'getSimilarSinger',
		category: 'singer',
		method: 'GET',
		path: '/getSimilarSinger',
		description: 'List singers similar to the given singer MID.',
		queryParams: params([{ name: 'singermid', required: true }]),
	},
	{
		name: 'getSingerAlbum',
		category: 'singer',
		method: 'GET',
		path: '/getSingerAlbum',
		description: 'List albums for a singer.',
		queryParams: params([
			{ name: 'singermid', required: true },
			{ name: 'limit', defaultValue: 5 },
			{ name: 'page', defaultValue: 0 },
		]),
	},
	{
		name: 'getSingerHotsong',
		category: 'singer',
		method: 'GET',
		path: '/getSingerHotsong',
		description: 'List hot songs for a singer.',
		queryParams: params([
			{ name: 'singermid', required: true },
			{ name: 'limit', defaultValue: 5 },
			{ name: 'page', defaultValue: 0 },
		]),
	},
	{
		name: 'getSingerMv',
		category: 'singer',
		method: 'GET',
		path: '/getSingerMv',
		description: 'List MV entries for a singer.',
		queryParams: params([
			{ name: 'singermid', required: true },
			{ name: 'order', defaultValue: 'listen', enumValues: ['listen', 'time'] },
			{ name: 'num', defaultValue: 5 },
		]),
	},
	{
		name: 'getSingerDesc',
		category: 'singer',
		method: 'GET',
		path: '/getSingerDesc',
		description: 'Fetch singer description by singer MID.',
		queryParams: params([{ name: 'singermid', required: true }]),
	},
	{
		name: 'getSingerStarNum',
		category: 'singer',
		method: 'GET',
		path: '/getSingerStarNum',
		description: 'Fetch singer follower/star count by singer MID.',
		queryParams: params([{ name: 'singermid', required: true }]),
	},
	{
		name: 'getRadioLists',
		category: 'radio',
		method: 'GET',
		path: '/getRadioLists',
		description: 'List QQ Music radio categories and stations.',
	},
	{
		name: 'getDigitalAlbumLists',
		category: 'album',
		method: 'GET',
		path: '/getDigitalAlbumLists',
		description: 'List digital album sale charts.',
	},
	{
		name: 'getLyric',
		category: 'music',
		method: 'GET',
		path: '/getLyric',
		aliases: ['/getLyric/:songmid'],
		description: 'Fetch lyric content by song MID.',
		queryParams: params([{ name: 'songmid', required: true }, { name: 'isFormat' }, { name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getMusicPlay',
		category: 'music',
		method: 'GET',
		path: '/getMusicPlay',
		aliases: ['/getMusicPlay/:songmid'],
		description: 'Fetch playable audio URLs by song MID. Requires valid QQ Music login cookie; returns specific error message when unauthenticated.',
		queryParams: params([
			{ name: 'songmid', required: true },
			{ name: 'resType' },
			{ name: 'mediaId' },
			{ name: 'quality' },
			{ name: 'cookie' },
		]),
		cookieRequired: true,
		examples: [{ label: '128k play URL', params: { songmid: '0039MnYb0qxYhV', quality: '128', resType: 'play' } }],
	},
	{
		name: 'getAlbumInfo',
		category: 'album',
		method: 'GET',
		path: '/getAlbumInfo',
		aliases: ['/getAlbumInfo/:albummid'],
		description: 'Fetch album information by album MID.',
		queryParams: params([{ name: 'albummid', required: true }]),
	},
	{
		name: 'getComments',
		category: 'comments',
		method: 'GET',
		path: '/getComments',
		description: 'List comments for a song, playlist, or album resource.',
		queryParams: params([
			{ name: 'id', required: true, description: 'Comment target resource ID.' },
			{ name: 'pagesize', defaultValue: 25 },
			{ name: 'pagenum' },
			{ name: 'cid' },
			{ name: 'cmd' },
			{ name: 'reqtype' },
			{ name: 'biztype' },
			{ name: 'rootcommentid' },
		]),
	},
	{
		name: 'getRecommend',
		category: 'recommend',
		method: 'GET',
		path: '/getRecommend',
		description: 'Fetch a public home-page recommendation bundle.',
	},
	{
		name: 'getRecommendBanner',
		category: 'recommend',
		method: 'GET',
		path: '/getRecommendBanner',
		description: 'Fetch public recommendation banner data.',
	},
	{
		name: 'getTopLists',
		category: 'rank',
		method: 'GET',
		path: '/getTopLists',
		description: 'Fetch QQ Music ranking list metadata.',
	},
	{
		name: 'getRanks',
		category: 'rank',
		method: 'GET',
		path: '/getRanks',
		description: 'Fetch ranking detail songs by top list ID.',
		queryParams: params([{ name: 'topId' }, { name: 'page', defaultValue: 0 }, { name: 'limit' }, { name: 'resolveMid', description: 'Resolve songmid for songs without it (calls detail API per-song).', defaultValue: false, enumValues: [false, true] }]),
	},
	{
		name: 'getTicketInfo',
		category: 'utility',
		method: 'GET',
		path: '/getTicketInfo',
		description: 'Fetch QQ Music ticket/show information.',
	},
	{
		name: 'getImageUrl',
		category: 'utility',
		method: 'GET',
		path: '/getImageUrl',
		description: 'Build a QQ Music album image URL from an image MID.',
		queryParams: params([
			{ name: 'id', required: true, example: '000MkMni19ClKG' },
			{ name: 'size', enumValues: ['150x150', '300x300', '500x500', '800x800'] },
			{ name: 'maxAge' },
		]),
		examples: [{ label: 'Album cover', params: { id: '000MkMni19ClKG', size: '300x300', maxAge: 2592000 } }],
	},
	{
		name: 'getQQLoginQr',
		category: 'login',
		method: 'GET',
		path: '/getQQLoginQr',
		aliases: ['/user/getQQLoginQr'],
		description: 'Create a QQ login QR code session.',
	},
	{
		name: 'checkQQLoginQr',
		category: 'login',
		method: 'POST',
		path: '/checkQQLoginQr',
		aliases: ['/user/checkQQLoginQr'],
		description: 'Check a QQ login QR code session.',
	},
	{
		name: 'getDailyRecommend',
		category: 'recommend',
		method: 'GET',
		path: '/getDailyRecommend',
		description: 'Fetch daily recommended songs. Cookie improves personalization.',
		queryParams: params([{ name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getPrivateFM',
		category: 'recommend',
		method: 'GET',
		path: '/getPrivateFM',
		description: 'Fetch private FM recommendations. Cookie improves personalization.',
		queryParams: params([{ name: 'cookie' }]),
		cookieRequired: true,
	},
	{
		name: 'getNewSongs',
		category: 'recommend',
		method: 'GET',
		path: '/getNewSongs',
		description: 'Fetch new song releases by area/type.',
		queryParams: params([{ name: 'areaId' }, { name: 'limit' }]),
	},
	{
		name: 'getPersonalRecommend',
		category: 'recommend',
		method: 'GET',
		path: '/getPersonalRecommend',
		description: 'Fetch personalized recommendations by type.',
		queryParams: params([
			{ name: 'type', defaultValue: 1, enumValues: [1, 2, 3], description: '1 playlist, 2 radio, 3 MV.' },
			{ name: 'cookie' },
		]),
		cookieRequired: true,
	},
	{
		name: 'getSimilarSongs',
		category: 'recommend',
		method: 'GET',
		path: '/getSimilarSongs',
		description: 'Fetch songs similar to the given song MID.',
		queryParams: params([{ name: 'songmid', required: true }, { name: 'cookie' }]),
	},
	{
		name: 'getRelatedPlaylists',
		category: 'recommend',
		method: 'GET',
		path: '/getRelatedPlaylists',
		description: 'Fetch playlists related to a song ID.',
		queryParams: params([
			{ name: 'songid', required: true },
			{ name: 'sin' },
			{ name: 'lastId' },
			{ name: 'songType' },
		]),
	},
	{
		name: 'getRelatedMv',
		category: 'recommend',
		method: 'GET',
		path: '/getRelatedMv',
		description: 'Fetch MV entries related to a song ID.',
		queryParams: params([
			{ name: 'songid', required: true },
			{ name: 'songtype' },
			{ name: 'lastmvid' },
			{ name: 'limit' },
		]),
	},
	{
		name: 'getPlaylistTags',
		category: 'playlist',
		method: 'GET',
		path: '/getPlaylistTags',
		description: 'List playlist tags for getPlaylistsByTag.',
	},
	{
		name: 'getPlaylistsByTag',
		category: 'playlist',
		method: 'GET',
		path: '/getPlaylistsByTag',
		description: 'List playlists for a playlist tag ID.',
		queryParams: params([{ name: 'tagId' }, { name: 'page', defaultValue: 0 }, { name: 'num' }]),
	},
	{
		name: 'getHotComments',
		category: 'comments',
		method: 'GET',
		path: '/getHotComments',
		description: 'Fetch hot comments for a song, playlist, or album resource.',
		queryParams: params([
			{ name: 'id', required: true },
			{ name: 'type', defaultValue: 1, enumValues: [1, 2, 3], description: '1 song, 2 playlist, 3 album.' },
			{ name: 'page', defaultValue: 0 },
			{ name: 'pagesize' },
		]),
	},
	{
		name: 'getSingerListByArea',
		category: 'singer',
		method: 'GET',
		path: '/getSingerListByArea',
		description: 'List singers by simplified area, gender, and genre filters.',
		queryParams: params([
			{ name: 'area' },
			{ name: 'sex' },
			{ name: 'genre' },
			{ name: 'page' },
			{ name: 'pagesize', defaultValue: 80 },
		]),
	},
];

export const apiMetadata: ApiMetadataItem[] = rawApiMetadata.map(withDefaultParamMetadata);

export const apiMetadataPaths = apiMetadata.flatMap(item => [item.path, ...(item.aliases || [])]);
